// (6, 1); token = "}" shold be error ( bbe[br at line 5 causes this )
[Exposed=Window]
callback interface NodeFilter {
  // Constants for acceptNode()
  [bbe[br,Exposed=Window] unsigned short acceptNode(Node node);
};